services:
  postgres-task:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todoapp
    ports:
      - "5433:5432" # Different host port to avoid conflict
    volumes:
      - postgres-task-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-user:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ToDoOrNotToDo
      - POSTGRES_DB=ToDoOrNotToDo
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ToDoOrNotToDo" ]
      interval: 10s
      timeout: 5s
      retries: 5
  unleash-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: unleash
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash
    volumes:
      - unleash-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U unleash" ]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://unleash:unleash@unleash-db/unleash
      DATABASE_SSL: "false"
      UNLEASH_URL: http://localhost:4242
    depends_on:
      unleash-db:
        condition: service_healthy
   

  taskmicroservice:
    image: taskmicroservice
    build:
      context: .
      dockerfile: TaskMicroservice/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      postgres-task:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-task;Database=todoapp;Username=postgres;Password=postgres
  
  usermicroservice:
    image: usermicroservice
    build:
      context: .
      dockerfile: UserMicroservice/Dockerfile
    depends_on:
      postgres-user:
        condition: service_healthy
      unleash:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-user;Database=ToDoOrNotToDo;Username=ToDoOrNotToDo;Password=password
      - Unleash__ApiUrl=http://unleash:4242/api/
      - Unleash__ApiToken=default:development.unleash-insecure-api-token

volumes:
  postgres-task-data:
  postgres-user-data:
  unleash-db-data: