services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr
  
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  task-ms:
    image: task-ms
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: TaskMicroservice/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_CONNECTION_STRING=Host=postgres;Database=todoapp;Username=postgres;Password=postgres
    
  usermicroservice:
    image: usermicroservice
    build:
      context: .
      dockerfile: UserMicroservice/Dockerfile
  
volumes:
  postgres-data:
    