name: Task
description: Used to define a task.
title: "[TASK]: "
labels: ["task"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Description
      placeholder: Task description here.
