name: Task
description: Used to define a task.
title: "[TASK]: "
labels: task # Automatically assign the 'task' label
body:
  - type: markdown
    attributes:
      label: Description
      placeholder: Task description here.
