name: Build and Deploy Docker Services

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          # Extract tag name that triggered the workflow
          TAG_NAME=${GITHUB_REF#refs/tags/}

          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'ENDSSH'
            # Check if todo-or-not-todo directory exists, if not clone it
            if [ ! -d ~/todo-or-not-todo ]; then
              echo "Directory not found. Cloning repository..."
              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/todo-or-not-todo
            fi

            # Navigate to project directory
            cd ~/todo-or-not-todo

            # Pull latest code
            git fetch --all --tags
          
            # Checkout to the specific tag that triggered this workflow
            git checkout ${TAG_NAME}
          
            # Set environment variables for compose.yaml
            export UNLEASH_API_TOKEN="${{ secrets.UNLEASH_API_TOKEN }}"
            export SERVER_HOST="${{secrets.SERVER_HOST}}"

            # Create a temporary environment file with correct URLs for production build
            cat > src/environments/environment.production.ts << EOF
            export const environment = {
              production: true,
              taskMsBaseUrl: 'http://${SERVER_HOST}:1000/api/v1/tasks',
              userMsBaseUrl: 'http://${SERVER_HOST}:1001',
            };
            EOF

            # Start all services
            docker compose up -d

          ENDSSH


